### ISSUE TITLE
Null pointer exception processing in MainProcessor.getExcludes

### ISSUE THREAD

**Issue by wsargent** [pantsbuild/jarjar#24]
I'm attempting to shade Netty 4.0 to a different package, using SBT.  I'm using version 1.6.3.

Here's the exception:

```
java.lang.NullPointerException
	at org.pantsbuild.jarjar.MainProcessor.getExcludes(MainProcessor.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at JarJar$.apply(JarJar.scala:85)
	at $2c2eb61f4fcd4328d880$$anonfun$play$minusws$minusnetty$minusembedded$8.apply(build.sbt:52)
	at $2c2eb61f4fcd4328d880$$anonfun$play$minusws$minusnetty$minusembedded$8.apply(build.sbt:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This implicates https://github.com/pantsbuild/jarjar/blob/master/src/main/java/org/pantsbuild/jarjar/MainProcessor.java#L99 -- specifically `kp` is probably null:

```java
    private Set<String> getExcludes() {
        Set<String> result = new HashSet<String>();
        for (String exclude : kp.getExcludes()) {
            String name = exclude + ".class";
            String renamed = renames.get(name);
            result.add((renamed != null) ? renamed : name);
        }
        return result;
    }
```

The approach I'm using is based off Scala's jline embedding: https://github.com/scala/scala/blob/2.12.x/build.sbt#L483

The test project is available under  https://github.com/wsargent/test-shade/tree/null-pointer-exception -- note the `null-pointer-exception` branch.

To reproduce, install sbt, then type `sbt compile` at a command prompt.

**Comment by wsargent** [comment]
Okay, this is actually happening on the SBT task side -- specifically, `getExcludes` is being called directly through reflection with the safeties off https://github.com/wsargent/test-shade/blob/null-pointer-exception/project/JarJar.scala#L83

```scala
val getter = processor.getClass.getDeclaredMethod("getExcludes")
    getter.setAccessible(true)
    val excludes = getter.invoke(processor).asInstanceOf[java.util.Set[String]].asScala
    val excluded = excludes.map { name =>
      val f: File = outdir / name
      if(f.exists && !f.delete())
        throw new IOException("Failed to delete excluded file $f")
      f
    }
```
